// @routes-hash 984fc68796e449bda62d3ed2ce506864
import { Express } from "express";

import route1 from "./routes/artStyle/getArtStyle";
import route2 from "./routes/assets/addAssets";
import route3 from "./routes/assets/delAssets";
import route4 from "./routes/assets/delAssetsImage";
import route5 from "./routes/assets/generateAssets";
import route6 from "./routes/assets/getAssets";
import route7 from "./routes/assets/getImage";
import route8 from "./routes/assets/getScriptList";
import route9 from "./routes/assets/polishAssetsPrompt";
import route10 from "./routes/assets/saveAssets";
import route11 from "./routes/assets/updateAssets";
import route12 from "./routes/audio/batchGenerateSpeech";
import route13 from "./routes/audio/generateBatchTTS";
import route14 from "./routes/audio/generateScriptAudio";
import route15 from "./routes/audio/generateSpeech";
import route16 from "./routes/audio/getAudioStatus";
import route17 from "./routes/audio/previewVoice";
import route18 from "./routes/batch/cancelBatch";
import route19 from "./routes/batch/createBatch";
import route20 from "./routes/batch/getBatchStatus";
import route21 from "./routes/batch/listBatches";
import route22 from "./routes/character/addCharacter";
import route23 from "./routes/character/bindCharacterVoice";
import route24 from "./routes/character/delCharacter";
import route25 from "./routes/character/getCharacters";
import route26 from "./routes/character/getCharacterStates";
import route27 from "./routes/character/getGlobalCharacters";
import route28 from "./routes/character/importFromAssets";
import route29 from "./routes/character/updateCharacter";
import route30 from "./routes/character/updateCharacterState";
import route155 from "./routes/character/saveIdentity";
import route156 from "./routes/character/getIdentities";
import route157 from "./routes/character/generateReference";
import route158 from "./routes/character/extractIdentity";
import route31 from "./routes/cost/estimateCost";
import route32 from "./routes/cost/getDailySummary";
import route33 from "./routes/cost/setBudget";
import route34 from "./routes/dashboard/getProductionStats";
import route35 from "./routes/distribution/autoGenerate";
import route36 from "./routes/distribution/getPublishHistory";
import route37 from "./routes/distribution/getRecommendations";
import route38 from "./routes/distribution/getTrending";
import route39 from "./routes/distribution/publish";
import route40 from "./routes/distribution/publishAll";
import route41 from "./routes/evolution/addVariable";
import route42 from "./routes/evolution/evolve";
import route43 from "./routes/evolution/generateFromGenome";
import route44 from "./routes/evolution/getPopulation";
import route45 from "./routes/evolution/getVariablePool";
import route46 from "./routes/evolution/initPopulation";
import route47 from "./routes/evolution/updateVariableScore";
import route48 from "./routes/factory/generateScript";
import route49 from "./routes/factory/getProductionStatus";
import route50 from "./routes/factory/runOnce";
import route51 from "./routes/factory/startProduction";
import route52 from "./routes/factory/stopProduction";
import route53 from "./routes/factory/validateScript";
import route54 from "./routes/marketplace/getTemplates";
import route55 from "./routes/marketplace/publishTemplate";
import route56 from "./routes/novel/addNovel";
import route57 from "./routes/novel/delNovel";
import route58 from "./routes/novel/getNovel";
import route59 from "./routes/novel/updateNovel";
import route60 from "./routes/other/clearDatabase";
import route61 from "./routes/other/deleteAllData";
import route62 from "./routes/other/getCaptcha";
import route63 from "./routes/other/login";
import route64 from "./routes/other/testAI";
import route65 from "./routes/other/testImage";
import route66 from "./routes/other/testVideo";
import route67 from "./routes/outline/addOutline";
import route68 from "./routes/outline/agentsOutline";
import route69 from "./routes/outline/delOutline";
import route70 from "./routes/outline/getHistory";
import route71 from "./routes/outline/getOutline";
import route72 from "./routes/outline/getPartScript";
import route73 from "./routes/outline/getStoryline";
import route74 from "./routes/outline/setHistory";
import route75 from "./routes/outline/updateOutline";
import route76 from "./routes/outline/updateScript";
import route77 from "./routes/outline/updateStoryline";
import route78 from "./routes/project/addProject";
import route79 from "./routes/project/autoSave";
import route80 from "./routes/project/cloneProject";
import route81 from "./routes/project/delProject";
import route82 from "./routes/project/getProject";
import route83 from "./routes/project/getProjectCount";
import route84 from "./routes/project/getProjectDashboard";
import route85 from "./routes/project/getSingleProject";
import route86 from "./routes/project/updateProject";
import route87 from "./routes/prompt/getPrompts";
import route88 from "./routes/prompt/updatePrompt";
import route89 from "./routes/queue/getQueueStats";
import route90 from "./routes/queue/pauseQueue";
import route91 from "./routes/score/getScores";
import route92 from "./routes/score/scoreProject";
import route93 from "./routes/score/submitMetrics";
import route94 from "./routes/script/generateScriptApi";
import route95 from "./routes/script/generateScriptSave";
import route96 from "./routes/script/geScriptApi";
import route97 from "./routes/script/getScriptVersions";
import route98 from "./routes/script/rewriteScript";
import route99 from "./routes/script/saveScriptVersion";
import route100 from "./routes/setting/addModel";
import route101 from "./routes/setting/configurationModel";
import route102 from "./routes/setting/delModel";
import route103 from "./routes/setting/getAiModelList";
import route104 from "./routes/setting/getAiModelMap";
import route105 from "./routes/setting/getLog";
import route106 from "./routes/setting/getSetting";
import route107 from "./routes/setting/getVideoModelDetail";
import route108 from "./routes/setting/getVideoModelList";
import route109 from "./routes/setting/updateModel";
import route110 from "./routes/storyboard/batchGenerateShots";
import route111 from "./routes/storyboard/batchReviewStoryboard";
import route112 from "./routes/storyboard/batchSuperScoreImage";
import route113 from "./routes/storyboard/chatStoryboard";
import route114 from "./routes/storyboard/delStoryboard";
import route115 from "./routes/storyboard/generateShotImage";
import route116 from "./routes/storyboard/generateVideoPrompt";
import route117 from "./routes/storyboard/getStoryboard";
import route118 from "./routes/storyboard/keepStoryboard";
import route119 from "./routes/storyboard/reviewStoryboard";
import route120 from "./routes/storyboard/saveStoryboard";
import route121 from "./routes/storyboard/saveStructuredShots";
import route122 from "./routes/storyboard/storyboardImageEdit";
import route123 from "./routes/storyboard/uploadImage";
import route124 from "./routes/system/flushCache";
import route125 from "./routes/system/getCacheStats";
import route126 from "./routes/system/getSystemStats";
import route127 from "./routes/task/addTask";
import route128 from "./routes/task/cancelTask";
import route129 from "./routes/task/getMyTaskApi";
import route130 from "./routes/task/getTaskCategories";
import route131 from "./routes/task/taskDetails";
import route132 from "./routes/template/addTemplate";
import route133 from "./routes/template/generateFromTemplate";
import route134 from "./routes/template/getTopTemplates";
import route135 from "./routes/template/getViralTemplates";
import route136 from "./routes/template/useTemplate";
import route137 from "./routes/user/getUser";
import route138 from "./routes/user/saveUser";
import route139 from "./routes/video/addVideo";
import route140 from "./routes/video/addVideoConfig";
import route141 from "./routes/video/batchGenerateVideo";
import route142 from "./routes/video/buildTimeline";
import route143 from "./routes/video/deleteVideoConfig";
import route144 from "./routes/video/generatePrompt";
import route145 from "./routes/video/generateSubtitles";
import route146 from "./routes/video/generateVideo";
import route147 from "./routes/video/getManufacturer";
import route148 from "./routes/video/getVideo";
import route149 from "./routes/video/getVideoConfigs";
import route150 from "./routes/video/getVideoModel";
import route151 from "./routes/video/getVideoStoryboards";
import route152 from "./routes/video/reviseVideoStoryboards";
import route153 from "./routes/video/saveVideo";
import route154 from "./routes/video/upDateVideoConfig";
import route159 from "./routes/storyboard/parseDSL";
import route160 from "./routes/video/getVideoConstraints";
import route161 from "./routes/video/saveVideoConstraints";
import route162 from "./routes/batch/createTemplate";
import route163 from "./routes/batch/createJob";
import route164 from "./routes/batch/getProgress";
import route165 from "./routes/batch/getTemplates";
import route166 from "./routes/audio/generateEmotionVoice";
import route167 from "./routes/audio/batchDialogue";
import route168 from "./routes/project/getAntiDrift";
import route169 from "./routes/project/saveAntiDrift";
import route170 from "./routes/viral/analyze";
import route171 from "./routes/viral/generate";
import route172 from "./routes/viral/score";
import route173 from "./routes/viral/templates";
import route174 from "./routes/series/create";
import route175 from "./routes/series/getDetail";
import route176 from "./routes/series/list";
import route177 from "./routes/series/generatePlan";
import route178 from "./routes/series/materialize";

export default async (app: Express) => {
  app.use("/artStyle/getArtStyle", route1);
  app.use("/assets/addAssets", route2);
  app.use("/assets/delAssets", route3);
  app.use("/assets/delAssetsImage", route4);
  app.use("/assets/generateAssets", route5);
  app.use("/assets/getAssets", route6);
  app.use("/assets/getImage", route7);
  app.use("/assets/getScriptList", route8);
  app.use("/assets/polishAssetsPrompt", route9);
  app.use("/assets/saveAssets", route10);
  app.use("/assets/updateAssets", route11);
  app.use("/audio/batchGenerateSpeech", route12);
  app.use("/audio/generateBatchTTS", route13);
  app.use("/audio/generateScriptAudio", route14);
  app.use("/audio/generateSpeech", route15);
  app.use("/audio/getAudioStatus", route16);
  app.use("/audio/previewVoice", route17);
  app.use("/batch/cancelBatch", route18);
  app.use("/batch/createBatch", route19);
  app.use("/batch/getBatchStatus", route20);
  app.use("/batch/listBatches", route21);
  app.use("/character/addCharacter", route22);
  app.use("/character/bindCharacterVoice", route23);
  app.use("/character/delCharacter", route24);
  app.use("/character/getCharacters", route25);
  app.use("/character/getCharacterStates", route26);
  app.use("/character/getGlobalCharacters", route27);
  app.use("/character/importFromAssets", route28);
  app.use("/character/updateCharacter", route29);
  app.use("/character/updateCharacterState", route30);
  app.use("/character/saveIdentity", route155);
  app.use("/character/getIdentities", route156);
  app.use("/character/generateReference", route157);
  app.use("/character/extractIdentity", route158);
  app.use("/cost/estimateCost", route31);
  app.use("/cost/getDailySummary", route32);
  app.use("/cost/setBudget", route33);
  app.use("/dashboard/getProductionStats", route34);
  app.use("/distribution/autoGenerate", route35);
  app.use("/distribution/getPublishHistory", route36);
  app.use("/distribution/getRecommendations", route37);
  app.use("/distribution/getTrending", route38);
  app.use("/distribution/publish", route39);
  app.use("/distribution/publishAll", route40);
  app.use("/evolution/addVariable", route41);
  app.use("/evolution/evolve", route42);
  app.use("/evolution/generateFromGenome", route43);
  app.use("/evolution/getPopulation", route44);
  app.use("/evolution/getVariablePool", route45);
  app.use("/evolution/initPopulation", route46);
  app.use("/evolution/updateVariableScore", route47);
  app.use("/factory/generateScript", route48);
  app.use("/factory/getProductionStatus", route49);
  app.use("/factory/runOnce", route50);
  app.use("/factory/startProduction", route51);
  app.use("/factory/stopProduction", route52);
  app.use("/factory/validateScript", route53);
  app.use("/marketplace/getTemplates", route54);
  app.use("/marketplace/publishTemplate", route55);
  app.use("/novel/addNovel", route56);
  app.use("/novel/delNovel", route57);
  app.use("/novel/getNovel", route58);
  app.use("/novel/updateNovel", route59);
  app.use("/other/clearDatabase", route60);
  app.use("/other/deleteAllData", route61);
  app.use("/other/getCaptcha", route62);
  app.use("/other/login", route63);
  app.use("/other/testAI", route64);
  app.use("/other/testImage", route65);
  app.use("/other/testVideo", route66);
  app.use("/outline/addOutline", route67);
  app.use("/outline/agentsOutline", route68);
  app.use("/outline/delOutline", route69);
  app.use("/outline/getHistory", route70);
  app.use("/outline/getOutline", route71);
  app.use("/outline/getPartScript", route72);
  app.use("/outline/getStoryline", route73);
  app.use("/outline/setHistory", route74);
  app.use("/outline/updateOutline", route75);
  app.use("/outline/updateScript", route76);
  app.use("/outline/updateStoryline", route77);
  app.use("/project/addProject", route78);
  app.use("/project/autoSave", route79);
  app.use("/project/cloneProject", route80);
  app.use("/project/delProject", route81);
  app.use("/project/getProject", route82);
  app.use("/project/getProjectCount", route83);
  app.use("/project/getProjectDashboard", route84);
  app.use("/project/getSingleProject", route85);
  app.use("/project/updateProject", route86);
  app.use("/prompt/getPrompts", route87);
  app.use("/prompt/updatePrompt", route88);
  app.use("/queue/getQueueStats", route89);
  app.use("/queue/pauseQueue", route90);
  app.use("/score/getScores", route91);
  app.use("/score/scoreProject", route92);
  app.use("/score/submitMetrics", route93);
  app.use("/script/generateScriptApi", route94);
  app.use("/script/generateScriptSave", route95);
  app.use("/script/geScriptApi", route96);
  app.use("/script/getScriptVersions", route97);
  app.use("/script/rewriteScript", route98);
  app.use("/script/saveScriptVersion", route99);
  app.use("/setting/addModel", route100);
  app.use("/setting/configurationModel", route101);
  app.use("/setting/delModel", route102);
  app.use("/setting/getAiModelList", route103);
  app.use("/setting/getAiModelMap", route104);
  app.use("/setting/getLog", route105);
  app.use("/setting/getSetting", route106);
  app.use("/setting/getVideoModelDetail", route107);
  app.use("/setting/getVideoModelList", route108);
  app.use("/setting/updateModel", route109);
  app.use("/storyboard/batchGenerateShots", route110);
  app.use("/storyboard/batchReviewStoryboard", route111);
  app.use("/storyboard/batchSuperScoreImage", route112);
  app.use("/storyboard/chatStoryboard", route113);
  app.use("/storyboard/delStoryboard", route114);
  app.use("/storyboard/generateShotImage", route115);
  app.use("/storyboard/generateVideoPrompt", route116);
  app.use("/storyboard/getStoryboard", route117);
  app.use("/storyboard/keepStoryboard", route118);
  app.use("/storyboard/reviewStoryboard", route119);
  app.use("/storyboard/saveStoryboard", route120);
  app.use("/storyboard/saveStructuredShots", route121);
  app.use("/storyboard/storyboardImageEdit", route122);
  app.use("/storyboard/uploadImage", route123);
  app.use("/system/flushCache", route124);
  app.use("/system/getCacheStats", route125);
  app.use("/system/getSystemStats", route126);
  app.use("/task/addTask", route127);
  app.use("/task/cancelTask", route128);
  app.use("/task/getMyTaskApi", route129);
  app.use("/task/getTaskCategories", route130);
  app.use("/task/taskDetails", route131);
  app.use("/template/addTemplate", route132);
  app.use("/template/generateFromTemplate", route133);
  app.use("/template/getTopTemplates", route134);
  app.use("/template/getViralTemplates", route135);
  app.use("/template/useTemplate", route136);
  app.use("/user/getUser", route137);
  app.use("/user/saveUser", route138);
  app.use("/video/addVideo", route139);
  app.use("/video/addVideoConfig", route140);
  app.use("/video/batchGenerateVideo", route141);
  app.use("/video/buildTimeline", route142);
  app.use("/video/deleteVideoConfig", route143);
  app.use("/video/generatePrompt", route144);
  app.use("/video/generateSubtitles", route145);
  app.use("/video/generateVideo", route146);
  app.use("/video/getManufacturer", route147);
  app.use("/video/getVideo", route148);
  app.use("/video/getVideoConfigs", route149);
  app.use("/video/getVideoModel", route150);
  app.use("/video/getVideoStoryboards", route151);
  app.use("/video/reviseVideoStoryboards", route152);
  app.use("/video/saveVideo", route153);
  app.use("/video/upDateVideoConfig", route154);
  app.use("/storyboard/parseDSL", route159);
  app.use("/video/getVideoConstraints", route160);
  app.use("/video/saveVideoConstraints", route161);
  app.use("/batch/createTemplate", route162);
  app.use("/batch/createJob", route163);
  app.use("/batch/getProgress", route164);
  app.use("/batch/getTemplates", route165);
  app.use("/audio/generateEmotionVoice", route166);
  app.use("/audio/batchDialogue", route167);
  app.use("/project/getAntiDrift", route168);
  app.use("/project/saveAntiDrift", route169);
  app.use("/viral/analyze", route170);
  app.use("/viral/generate", route171);
  app.use("/viral/score", route172);
  app.use("/viral/templates", route173);
  app.use("/series/create", route174);
  app.use("/series/getDetail", route175);
  app.use("/series/list", route176);
  app.use("/series/generatePlan", route177);
  app.use("/series/materialize", route178);
}
