// @routes-hash d8b95db972bd0ab01243d87d89a004f0
import { Express } from "express";

import route1 from "./routes/artStyle/getArtStyle";
import route2 from "./routes/assets/addAssets";
import route3 from "./routes/assets/delAssets";
import route4 from "./routes/assets/delAssetsImage";
import route5 from "./routes/assets/generateAssets";
import route6 from "./routes/assets/getAssets";
import route7 from "./routes/assets/getImage";
import route8 from "./routes/assets/getScriptList";
import route9 from "./routes/assets/polishAssetsPrompt";
import route10 from "./routes/assets/saveAssets";
import route11 from "./routes/assets/updateAssets";
import route12 from "./routes/novel/addNovel";
import route13 from "./routes/novel/delNovel";
import route14 from "./routes/novel/getNovel";
import route15 from "./routes/novel/updateNovel";
import route16 from "./routes/other/clearDatabase";
import route17 from "./routes/other/deleteAllData";
import route18 from "./routes/other/getCaptcha";
import route19 from "./routes/other/login";
import route20 from "./routes/other/testAI";
import route21 from "./routes/other/testImage";
import route22 from "./routes/other/testVideo";
import route23 from "./routes/outline/addOutline";
import route24 from "./routes/outline/agentsOutline";
import route25 from "./routes/outline/delOutline";
import route26 from "./routes/outline/getHistory";
import route27 from "./routes/outline/getOutline";
import route28 from "./routes/outline/getPartScript";
import route29 from "./routes/outline/getStoryline";
import route30 from "./routes/outline/setHistory";
import route31 from "./routes/outline/updateOutline";
import route32 from "./routes/outline/updateScript";
import route33 from "./routes/outline/updateStoryline";
import route34 from "./routes/project/addProject";
import route35 from "./routes/project/delProject";
import route36 from "./routes/project/getProject";
import route37 from "./routes/project/getProjectCount";
import route38 from "./routes/project/getSingleProject";
import route39 from "./routes/project/updateProject";
import route40 from "./routes/prompt/getPrompts";
import route41 from "./routes/prompt/updatePrompt";
import route42 from "./routes/script/generateScriptApi";
import route43 from "./routes/script/generateScriptSave";
import route44 from "./routes/script/geScriptApi";
import route45 from "./routes/setting/addModel";
import route46 from "./routes/setting/configurationModel";
import route47 from "./routes/setting/delModel";
import route48 from "./routes/setting/getAiModelList";
import route49 from "./routes/setting/getAiModelMap";
import route50 from "./routes/setting/getLog";
import route51 from "./routes/setting/getSetting";
import route52 from "./routes/setting/getVideoModelDetail";
import route53 from "./routes/setting/getVideoModelList";
import route54 from "./routes/setting/updateModel";
import route55 from "./routes/storyboard/batchSuperScoreImage";
import route56 from "./routes/storyboard/chatStoryboard";
import route57 from "./routes/storyboard/delStoryboard";
import route58 from "./routes/storyboard/generateShotImage";
import route59 from "./routes/storyboard/generateVideoPrompt";
import route60 from "./routes/storyboard/getStoryboard";
import route61 from "./routes/storyboard/keepStoryboard";
import route62 from "./routes/storyboard/saveStoryboard";
import route63 from "./routes/storyboard/storyboardImageEdit";
import route64 from "./routes/storyboard/uploadImage";
import route65 from "./routes/task/getMyTaskApi";
import route66 from "./routes/task/getTaskCategories";
import route67 from "./routes/task/taskDetails";
import route68 from "./routes/user/getUser";
import route69 from "./routes/user/saveUser";
import route70 from "./routes/video/addVideo";
import route71 from "./routes/video/addVideoConfig";
import route72 from "./routes/video/deleteVideoConfig";
import route73 from "./routes/video/generatePrompt";
import route74 from "./routes/video/generateVideo";
import route75 from "./routes/video/getManufacturer";
import route76 from "./routes/video/getVideo";
import route77 from "./routes/video/getVideoConfigs";
import route78 from "./routes/video/getVideoModel";
import route79 from "./routes/video/getVideoStoryboards";
import route80 from "./routes/video/reviseVideoStoryboards";
import route81 from "./routes/video/saveVideo";
import route82 from "./routes/video/upDateVideoConfig";
import route83 from "./routes/character/getCharacters";
import route84 from "./routes/character/bindCharacterVoice";

export default async (app: Express) => {
  app.use("/artStyle/getArtStyle", route1);
  app.use("/assets/addAssets", route2);
  app.use("/assets/delAssets", route3);
  app.use("/assets/delAssetsImage", route4);
  app.use("/assets/generateAssets", route5);
  app.use("/assets/getAssets", route6);
  app.use("/assets/getImage", route7);
  app.use("/assets/getScriptList", route8);
  app.use("/assets/polishAssetsPrompt", route9);
  app.use("/assets/saveAssets", route10);
  app.use("/assets/updateAssets", route11);
  app.use("/novel/addNovel", route12);
  app.use("/novel/delNovel", route13);
  app.use("/novel/getNovel", route14);
  app.use("/novel/updateNovel", route15);
  app.use("/other/clearDatabase", route16);
  app.use("/other/deleteAllData", route17);
  app.use("/other/getCaptcha", route18);
  app.use("/other/login", route19);
  app.use("/other/testAI", route20);
  app.use("/other/testImage", route21);
  app.use("/other/testVideo", route22);
  app.use("/outline/addOutline", route23);
  app.use("/outline/agentsOutline", route24);
  app.use("/outline/delOutline", route25);
  app.use("/outline/getHistory", route26);
  app.use("/outline/getOutline", route27);
  app.use("/outline/getPartScript", route28);
  app.use("/outline/getStoryline", route29);
  app.use("/outline/setHistory", route30);
  app.use("/outline/updateOutline", route31);
  app.use("/outline/updateScript", route32);
  app.use("/outline/updateStoryline", route33);
  app.use("/project/addProject", route34);
  app.use("/project/delProject", route35);
  app.use("/project/getProject", route36);
  app.use("/project/getProjectCount", route37);
  app.use("/project/getSingleProject", route38);
  app.use("/project/updateProject", route39);
  app.use("/prompt/getPrompts", route40);
  app.use("/prompt/updatePrompt", route41);
  app.use("/script/generateScriptApi", route42);
  app.use("/script/generateScriptSave", route43);
  app.use("/script/geScriptApi", route44);
  app.use("/setting/addModel", route45);
  app.use("/setting/configurationModel", route46);
  app.use("/setting/delModel", route47);
  app.use("/setting/getAiModelList", route48);
  app.use("/setting/getAiModelMap", route49);
  app.use("/setting/getLog", route50);
  app.use("/setting/getSetting", route51);
  app.use("/setting/getVideoModelDetail", route52);
  app.use("/setting/getVideoModelList", route53);
  app.use("/setting/updateModel", route54);
  app.use("/storyboard/batchSuperScoreImage", route55);
  app.use("/storyboard/chatStoryboard", route56);
  app.use("/storyboard/delStoryboard", route57);
  app.use("/storyboard/generateShotImage", route58);
  app.use("/storyboard/generateVideoPrompt", route59);
  app.use("/storyboard/getStoryboard", route60);
  app.use("/storyboard/keepStoryboard", route61);
  app.use("/storyboard/saveStoryboard", route62);
  app.use("/storyboard/storyboardImageEdit", route63);
  app.use("/storyboard/uploadImage", route64);
  app.use("/task/getMyTaskApi", route65);
  app.use("/task/getTaskCategories", route66);
  app.use("/task/taskDetails", route67);
  app.use("/user/getUser", route68);
  app.use("/user/saveUser", route69);
  app.use("/video/addVideo", route70);
  app.use("/video/addVideoConfig", route71);
  app.use("/video/deleteVideoConfig", route72);
  app.use("/video/generatePrompt", route73);
  app.use("/video/generateVideo", route74);
  app.use("/video/getManufacturer", route75);
  app.use("/video/getVideo", route76);
  app.use("/video/getVideoConfigs", route77);
  app.use("/video/getVideoModel", route78);
  app.use("/video/getVideoStoryboards", route79);
  app.use("/video/reviseVideoStoryboards", route80);
  app.use("/video/saveVideo", route81);
  app.use("/video/upDateVideoConfig", route82);
  app.use("/character/getCharacters", route83);
  app.use("/character/bindCharacterVoice", route84);
}
